//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinUI.Analyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinUI.Analyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Microsoft.UI.Xaml.Data;
        ///using Microsoft.UI.Xaml.Interop;
        ///using System;
        ///using System.Collections;
        ///using System.Collections.Generic;
        ///using System.Collections.ObjectModel;
        ///using System.Collections.Specialized;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace AppUIBasics
        ///{
        ///    // .NET collection types are tightly coupled with WUX types - e.g., ObservableCollection&lt;T&gt;
        ///    // maps to WUX.INotifyCollectionChanged, and creates WUX.NotifyCollectionChangedEventArgs
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CollectionsInterop {
            get {
                return ResourceManager.GetString("CollectionsInterop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.ApplicationModel.Preview.InkWorkspace
        ///Windows.UI.Input.Inking
        ///Windows.UI.Input.Inking.Analysis
        ///Windows.UI.Input.Inking.Core
        ///Windows.UI.Input.Inking.Preview
        ///Windows.UI.Xaml.Media.AcrylicBackgroundSource.
        /// </summary>
        public static string deprecatedUseAnalyzer {
            get {
                return ResourceManager.GetString("deprecatedUseAnalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UWP Apps must explicitly target Microsoft.UI.Xaml.LaunchActivatedEventArgs in the OnLaunched Method parameter type..
        /// </summary>
        public static string EventArgs_Description {
            get {
                return ResourceManager.GetString("EventArgs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnLaunched must use Microsoft.UI.Xaml.LaunchActivatedEventArgs.
        /// </summary>
        public static string EventArgs_MessageFormat {
            get {
                return ResourceManager.GetString("EventArgs_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LaunchActivatedEventArgs Ambiguous Namespace.
        /// </summary>
        public static string EventArgs_Title {
            get {
                return ResourceManager.GetString("EventArgs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This API is not supported in WinUI3. This code may not compile or behave as expected..
        /// </summary>
        public static string Incompatible_Description {
            get {
                return ResourceManager.GetString("Incompatible_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible With WinUI3.
        /// </summary>
        public static string Incompatible_MessageFormat {
            get {
                return ResourceManager.GetString("Incompatible_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible API.
        /// </summary>
        public static string Incompatible_Title {
            get {
                return ResourceManager.GetString("Incompatible_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Namespace should be updated to Microsoft.
        /// </summary>
        public static string Namespace_Description {
            get {
                return ResourceManager.GetString("Namespace_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Windows Namespace instead of Microsoft.
        /// </summary>
        public static string Namespace_MessageFormat {
            get {
                return ResourceManager.GetString("Namespace_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Namespace should be Microsoft.
        /// </summary>
        public static string Namespace_Title {
            get {
                return ResourceManager.GetString("Namespace_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.UI.Xaml
        ///Windows.UI.Colors
        ///Windows.UI.ColorHelper
        ///Windows.UI.Composition
        ///Windows.UI.Text
        ///Windows.UI.Input
        ///Windows.System.DispatcherQueue
        ///Windows.System.DispatcherQueueController
        ///Windows.System.DispatcherQueueHandler
        ///Windows.System.DispatcherQueuePriority
        ///Windows.System.DispatcherQueueShutdownStartingEventArgs
        ///Windows.System.DispatcherQueueTimer.
        /// </summary>
        public static string namespaceAnalyzer {
            get {
                return ResourceManager.GetString("namespaceAnalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObservableCollection&lt;T&gt; illegal use..
        /// </summary>
        public static string UWPObservable_Description {
            get {
                return ResourceManager.GetString("UWPObservable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to illegal type, Impement with Interops..
        /// </summary>
        public static string UWPObservable_MessageFormat {
            get {
                return ResourceManager.GetString("UWPObservable_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObservableCollection&lt;T&gt; should use new projection..
        /// </summary>
        public static string UWPObservable_Title {
            get {
                return ResourceManager.GetString("UWPObservable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UWP Projections have moved..
        /// </summary>
        public static string UWPProjection_Description {
            get {
                return ResourceManager.GetString("UWPProjection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must use Microsoft namespace..
        /// </summary>
        public static string UWPProjection_MessageFormat {
            get {
                return ResourceManager.GetString("UWPProjection_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UWP Projections moved to Microsoft.*.
        /// </summary>
        public static string UWPProjection_Title {
            get {
                return ResourceManager.GetString("UWPProjection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Struct Constructor instead of Helper Method..
        /// </summary>
        public static string UWPStruct_Description {
            get {
                return ResourceManager.GetString("UWPStruct_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to should use Helper Method instead of Constructor..
        /// </summary>
        public static string UWPStruct_MessageFormat {
            get {
                return ResourceManager.GetString("UWPStruct_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UWP Struct illegal Constructor use..
        /// </summary>
        public static string UWPStruct_Title {
            get {
                return ResourceManager.GetString("UWPStruct_Title", resourceCulture);
            }
        }
    }
}
